// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransferLatinToGeorgian.Data.Source;

#nullable disable

namespace TransferLatinToGeorgian.Migrations
{
    [DbContext(typeof(SourceDbContext))]
    partial class SourceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransferLatinToGeorgian.Data.Source.Entities.reestri", b =>
                {
                    b.Property<string>("DMONAC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REGMDAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dabWeli")
                        .HasColumnType("datetime2");

                    b.Property<string>("gvari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mamisSaxeli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mocmobisNomeri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("piradi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quCa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("regTariRi")
                        .HasColumnType("datetime2");

                    b.Property<string>("saxeli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("sqesi")
                        .HasColumnType("float");

                    b.ToTable("reestri", (string)null);
                });

            modelBuilder.Entity("TransferLatinToGeorgian.Data.Source.Entities.reestriGeo", b =>
                {
                    b.Property<string>("piradi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DMONAC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REGMDAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dabWeli")
                        .HasColumnType("datetime2");

                    b.Property<string>("gvari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mamisSaxeli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mocmobisNomeri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quCa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("regTariRi")
                        .HasColumnType("datetime2");

                    b.Property<string>("saxeli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("sqesi")
                        .HasColumnType("float");

                    b.HasKey("piradi");

                    b.ToTable("reestriGeos");
                });
#pragma warning restore 612, 618
        }
    }
}
